#dobbo配置
dubbo:
  application:
    name: gmall-pms
  registry:
    protocol: zookeeper
    address: 47.93.32.124:2181
  protocol:
    name: dubbo
    port: 20981
  consumer:
    check: false
server:
  port: 9002

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  redis:
    host: 47.93.32.124 #这里把host写错成url报错了
    password: redispassword
    database: 15
