spring:
  datasource:
    url: jdbc:mysql://47.93.32.124:3307/gmall_ums?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gmall-ums
#dubbo 配置
dubbo:
  application:
    name: gmall-ums
  registry:
    protocol: zookeeper
    address: 47.93.32.124:2181 #注册中心
  #scan:
    #base-packages: 配置了EnableDubbo这里就不需要配置了
  protocol:
    name: dubbo
    port: 20980
  consumer:
    check: false
server:
  port: 9001